"""Every mutant this project has been verified against.

One catalogue, in the repository, so "all mutations caught" is a claim anyone
can re-run instead of one they have to take on trust. Each entry is
(label, path, original, mutated) and the original must still appear in the
file -- `audit/mutate.py` reports a stale anchor as a FAILURE, because a mutant
whose anchor has drifted is a guard that has silently stopped testing anything.

`tests/test_labelled_ingest.py` asserts every anchor still matches, which is
the cheap half of a mutation run: it executes nothing and catches drift the
moment it happens.
"""

MUTANTS = [
    ('set code: brief derivation removed',
     'ingest/catalog_sources.py',
     '    ident = str(find(hit, "id") or "")',
     '    return ""\n    ident = str(find(hit, "id") or "")'),
    ('set code: split on the FIRST hyphen',
     'ingest/catalog_sources.py',
     '        return ident.rsplit("-", 1)[0]',
     '        return ident.split("-", 1)[0]'),
    ('set code: localId suffix ignored',
     'ingest/catalog_sources.py',
     '    if ident and local and ident.endswith(f"-{local}"):',
     '    if False:'),
    ('dropped rows not counted',
     'ingest/catalog_sources.py',
     '                self.dropped_no_identity += 1',
     '                pass'),
    ('sealed: a missing type field means not-a-card',
     'ingest/catalog.py',
     '    if not present:\n        return False',
     '    if not present:\n        return True'),
    ('sealed: rarity no longer has to be absent',
     'ingest/catalog.py',
     '    return (all(hit[k] in (None, "") for k in present)\n            and hit.get("rarity") in (None, ""))',
     '    return all(hit[k] in (None, "") for k in present)'),
    ('sealed: the drop is silent',
     'ingest/catalog.py',
     '            self.note_not_a_card(game, language, number, find(hit, "name"))',
     '            pass'),
    ('set size: aliases ignored',
     'ingest/catalog.py',
     '        code = RIFTBOUND_SET_ALIASES.get(key.lower(), key.upper())',
     '        code = key.upper()'),
    ('unreadable number: sample not kept',
     'ingest/catalog.py',
     '            self.note_unbandable(game, language, rarity, number)',
     '            pass'),
    ('unreadable number: banded base instead of unknown',
     'ingest/rarity.py',
     '    if parsed.kind == "unreadable":',
     '    if False:'),
    ('deliberate unknowns are treated as unclassified',
     'ingest/rarity.py',
     '    return _BY_GAME.get(game, {}).get(normalise(rarity)) == UNKNOWN',
     '    return False'),
    ('429: breaker never trips',
     'ingest/base.py',
     '        elif self.rate_limit_hits >= self.stop_calling_after_rate_limits:',
     '        elif False:'),
    ('429: a closed adapter keeps calling',
     'ingest/base.py',
     '            if self.rate_limited:\n                raise RateLimited(',
     '            if False:\n                raise RateLimited('),
    ('429: Retry-After ignored',
     'ingest/base.py',
     '                              seconds=retry_after_seconds(response_headers))',
     '                              seconds=None)'),
    ('429: an hour-long Retry-After is honoured',
     'ingest/base.py',
     '        if wait is not None and wait > self.max_retry_after_seconds:',
     '        if False:'),
    ('Retry-After: only the integer form is read',
     'ingest/base.py',
     '            when = email.utils.parsedate_to_datetime(text)',
     '            when = None'),
    ('rate headers: not kept',
     'ingest/base.py',
     '            self.rate_headers.update(found)',
     '            pass'),
    ('cache: an undated entry counts as fresh',
     'ingest/catalog.py',
     '    if not stamp:\n        return None',
     '    if not stamp:\n        return 0.0'),
    ('cache: --force does not force',
     'ingest/catalog.py',
     '            if fresh and not force:',
     '            if fresh:'),
    ('cache: a cached combo reads as ok',
     'ingest/catalog.py',
     '                    "status": "catalog_from_cache", "cards": len(cards),',
     '                    "status": "ok", "cards": len(cards),'),
    ('cache: a failed refresh does not fall back',
     'ingest/catalog.py',
     '            elif cached.get("cards"):',
     '            elif False:'),
    ('cache: a cached combo is restamped with today',
     'ingest/catalog.py',
     '            as_of = (cache.get(combo) or {}).get("as_of")',
     '            as_of = entry.get("as_of")'),
    ('cache: an empty combo is stamped anyway',
     'ingest/catalog.py',
     '        if not cards:\n            # Nothing to remember.',
     '        if False:\n            # Nothing to remember.'),
    ('persist: zero cards accepted',
     'ingest/catalog.py',
     '    if total <= 0:',
     '    if False:'),
    ('persist: undated cards accepted',
     'ingest/catalog.py',
     '    if undated:',
     '    if False:'),
    ('fallback: serving reads as plain ok',
     'ingest/catalog.py',
     '            if deduped and primary and primary not in sources:',
     '            if False:'),
    ('429: a refused combo is called unreachable',
     'ingest/catalog.py',
     '                kind = ("apitcg_rate_limited" if isinstance(exc, RateLimited)',
     '                kind = ("apitcg_unreachable" if isinstance(exc, RateLimited)'),
    ('id suffix: parallels merge into base',
     'resolve/identity.py',
     '    match = _ID_SUFFIX.search(str(external_id or ""))',
     '    match = None'),
    ('id suffix: every parallel is the same token',
     'resolve/identity.py',
     '    return stem if index in ("", "1") else f"{stem}{index}"',
     '    return stem'),
    ('id suffix: an unknown suffix becomes base',
     'resolve/identity.py',
     '        return "unknown_" + match.group(1).lower() + match.group(2)',
     '        return None'),
    ('id suffix: applied to every game',
     'resolve/identity.py',
     '    if game is not None and game not in ID_SUFFIX_VARIANT_GAMES:\n        return None\n    match = _ID_SUFFIX',
     '    match = _ID_SUFFIX'),
    ('id suffix: loses to the rarity string',
     'ingest/catalog.py',
     '        variant = (variant_from_number(number, size, game)\n                   or variant_from_external_id(external_id, game)\n                   or _variant_of(rarity, name, language, game))',
     '        variant = (variant_from_number(number, size, game)\n                   or _variant_of(rarity, name, language, game)\n                   or variant_from_external_id(external_id, game))'),
    ('cache state: absent and empty collapse',
     'ingest/catalog.py',
     '    if not cached:\n        return "absent"',
     '    if not cached:\n        return "empty"'),
    ('cache state: undated reads as stale',
     'ingest/catalog.py',
     '    if age is None:\n        return "undated"',
     '    if age is None:\n        return "stale"'),
    ('cache state: --force reads as an ordinary refresh',
     'ingest/catalog.py',
     '    return "forced" if force else "fresh"',
     '    return "fresh"'),
    ('cache state: the threshold boundary flips',
     'ingest/catalog.py',
     '    if age >= max_age_days:\n        return "stale"',
     '    if age > max_age_days:\n        return "stale"'),
    ('cache state: not recorded on a re-enumerated combo',
     'ingest/catalog.py',
     '                "cache_state": state,\n                "age_days": None if age is None else round(age, 2),',
     '                "age_days": None if age is None else round(age, 2),'),
    ('the fresh-but-refreshed fault is not reported',
     'ingest/catalog.py',
     '    return (entry.get("cache_state") == "fresh"\n            and not str(entry.get("status", "")).startswith("catalog_from_cache"))',
     '    return False'),
    ('--force is reported as the fault',
     'ingest/catalog.py',
     '    return (entry.get("cache_state") == "fresh"',
     '    return (entry.get("cache_state") in ("fresh", "forced")'),
    ('preserve: an empty combo is committed over yesterday',
     'ingest/catalog.py',
     '    for combo, entry in sorted((previous or {}).items()):',
     '    for combo, entry in sorted({}.items()):'),
    ('preserve: a combo that shrank is resurrected',
     'ingest/catalog.py',
     '        if (catalog.get(combo) or {}).get("cards"):\n            continue',
     '        if False:\n            continue'),
    ('preserve: the reason it was empty is dropped',
     'ingest/catalog.py',
     '            "preserved_over": (combo_status.get(combo) or {}).get("status"),',
     '            "preserved_over": None,'),
    ('preserve: reads as plain ok',
     'ingest/catalog.py',
     '            "status": "catalog_from_cache_preserved",',
     '            "status": "ok",'),
    ('--no-cache erases instead of preserving',
     'ingest/catalog.py',
     '    previous = load_cached_catalog(args.out)\n    cache = {} if args.no_cache else previous',
     '    cache = {} if args.no_cache else load_cached_catalog(args.out)\n    previous = cache'),
    ('to_targets stamps from the freshness cache',
     'ingest/catalog.py',
     '                         builder.not_a_card, cache=previous,',
     '                         builder.not_a_card, cache=cache,'),
    ('totals: a cache-served run erases what we know',
     'ingest/catalog.py',
     '                         set_totals=merge_set_totals(\n                             load_set_totals(args.out), builder.set_totals))',
     '                         set_totals=builder.set_totals)'),
    ('totals: merging is a replacement after all',
     'ingest/catalog.py',
     '    merged = {lang: dict(sets) for lang, sets in (previous or {}).items()}',
     '    merged = {}'),
    ('totals: this run cannot correct a recorded count',
     'ingest/catalog.py',
     '        merged.setdefault(str(lang), {}).update(sets or {})',
     '        merged.setdefault(str(lang), {})'),
    ('totals: a regression is persistable',
     'ingest/catalog.py',
     '    if was and now < was:',
     '    if False:'),
    ('totals: the guard reads the overwritten file instead of git',
     'ingest/catalog.py',
     '    was, now = _committed_set_total_count(path), _set_total_count(raw)',
     '    was, now = _set_total_count(raw), _set_total_count(raw)'),
    ('persist step gated on the run succeeding',
     '.github/workflows/ingest.yml',
     "          always()\n          && steps.persist_check.outcome == 'success'",
     "          success()\n          && steps.persist_check.outcome == 'success'"),
    ('TC set code: F suffix not required',
     'resolve/identity.py',
     '    if len(code) <= len(suffix) or not code.lower().endswith(suffix.lower()):\n        return None',
     '    if False:\n        return None'),
    ('TC set code: comparison becomes case-sensitive',
     'resolve/identity.py',
     '    return parent.lower() == str(japanese_set_code or "").strip().lower()',
     '    return parent == str(japanese_set_code or "").strip()'),
    ("CN-S given CN-T's numbering behaviour",
     'resolve/identity.py',
     '    return language in NUMBERING_PARENT',
     '    return language in ("CN-T", "CN-S")'),
    ('confusable numbers: table ignored',
     'resolve/identity.py',
     '    entry = KNOWN_CONFUSABLE_NUMBERS.get((game, set_code, name))',
     '    entry = None'),
    ('ingest: confidence not required',
     'resolve/label_cli.py',
     'REQUIRED_FIELDS = ("card_uid", "game", "set_code", "number", "variant",\n                   "language", "name", "source", "confidence")',
     'REQUIRED_FIELDS = ("card_uid", "game", "set_code", "number", "variant",\n                   "language", "name", "source")'),
    ('ingest: an unknown confidence is accepted',
     'resolve/label_cli.py',
     '        if row.get("confidence") and row["confidence"] not in CONFIDENCE:',
     '        if False:'),
    ('ingest: the stated uid is trusted',
     'resolve/label_cli.py',
     '                if row["card_uid"] != expected:',
     '                if False:'),
    ('ingest: an unknown variant is accepted',
     'resolve/label_cli.py',
     '        if row.get("variant") and not is_variant(row["variant"],\n                                                 row.get("game")):',
     '        if False:'),
    ('ingest: known confusables are accepted',
     'resolve/label_cli.py',
     '        if confusable and row.get("number") in confusable["confusable"]:',
     '        if False:'),
    ('ingest: rejected rows are written anyway',
     'resolve/label_cli.py',
     '        if why:\n            rejected.append({"index": index, "row": row, "why": why})\n        else:\n            accepted.append(row)',
     '        rejected.append({"index": index, "row": row, "why": why}) if False else None\n        accepted.append(row)'),
    ('ingest: dry run writes',
     'resolve/label_cli.py',
     '    if accepted and not dry_run:',
     '    if accepted:'),
    ('ingest: a duplicate is silently merged',
     'resolve/label_cli.py',
     '        if not why and row["card_uid"] in existing:',
     '        if False:'),
    ('single_source promoted to ground truth',
     'resolve/label_cli.py',
     'SCORED = ("verified",)',
     'SCORED = ("verified", "single_source")'),
    ('gate: scores every row, not just verified',
     'tests/test_resolver_gate.py',
     '    return [c for c in data["cards"] if c.get("confidence") in SCORED]',
     '    return list(data["cards"])'),
    ('gate: pool breakdown collapses',
     'tests/test_resolver_gate.py',
     '    return collections.Counter(c.get("confidence", "unstated")\n                               for c in data["cards"])',
     '    return collections.Counter({"unstated": len(data["cards"])})'),
    ('set alias: not applied',
     'resolve/identity.py',
     '    entry = SET_CODE_ALIASES.get((game, language, str(set_code or "")))',
     '    entry = None'),
    ('set alias: unknown codes rewritten instead of passed through',
     'resolve/identity.py',
     '    return (entry["code"], entry) if entry else (set_code, None)',
     '    return (entry["code"], entry) if entry else ("", None)'),
    ('set alias: uid not rebuilt after renaming',
     'resolve/label_cli.py',
     '            if row.get("card_uid"):\n                row["card_uid"] = ":".join(',
     '            if False:\n                row["card_uid"] = ":".join('),
    ('supersede: fires without the flag',
     'resolve/label_cli.py',
     '            if (supersede_unstated\n                    and previous.get("confidence") == "unstated"',
     '            if (True\n                    and previous.get("confidence") == "unstated"'),
    ('supersede: applies to a stated confidence too',
     'resolve/label_cli.py',
     '                    and previous.get("confidence") == "unstated"',
     '                    and previous.get("confidence") is not None'),
    ('supersede: the old row is not removed',
     'resolve/label_cli.py',
     '        kept = [c for c in labelled.get("cards", [])\n                if c["card_uid"] not in replaced]',
     '        kept = list(labelled.get("cards", []))'),
    ('supersede: annotations are dropped',
     'resolve/label_cli.py',
     '                inherited = {k: v for k, v in previous.items()\n                             if k not in row and k not in _NOT_INHERITED}',
     '                inherited = {}'),
    ('supersede: provenance is inherited too',
     'resolve/label_cli.py',
     '_NOT_INHERITED = frozenset({"confidence", "source", "verified_from",\n                            "supersedes", "supersedes_confidence",\n                            "inherited_fields", "adjudication"})',
     '_NOT_INHERITED = frozenset()'),
    ('supersede: no reference recorded',
     'resolve/label_cli.py',
     '                row.update(supersedes=previous.get("card_uid"),',
     '                row.update(supersedes=None,'),
    ('blocking-on-real-data: silently skips everything',
     'tests/test_resolver_gate.py',
     '        if len(present) < 2:',
     '        if True:'),
    ("blocking-on-real-data: a row may resolve to another's identity",
     'tests/test_resolver_gate.py',
     '        for uid, resolved in got.items():\n            self.assertEqual(\n                resolved, uid,',
     '        for uid, resolved in got.items():\n            self.assertIsNotNone(\n                resolved,'),
    ('bridge: an unknown total falls back to the index',
     'resolve/identity.py',
     '    if set_total in (None, ""):\n        raise CannotBridge(\n            f"{catalog_number!r} carries no denominator and the set\'s official "',
     '    if False:\n        raise CannotBridge(\n            f"{catalog_number!r} carries no denominator and the set\'s official "'),
    ('bridge: printed_from_bare defaults a missing total',
     'resolve/identity.py',
     '    if set_total in (None, ""):\n        raise CannotBridge(\n            f"cannot derive a printed number for {bare_number!r}: the set\'s "',
     '    if False:\n        raise CannotBridge(\n            f"cannot derive a printed number for {bare_number!r}: the set\'s "'),
    ('bridge: two naked indices are compared',
     'resolve/identity.py',
     '    if left.kind == "bare" and right.kind == "bare":',
     '    if False:'),
    ('bridge: the denominator stops mattering',
     'resolve/identity.py',
     '    return (bare.index == printed.index and int(set_total) == printed.total',
     '    return (bare.index == printed.index and True'),
    ('bridge: set-prefixed numbers compared by parsed index',
     'resolve/identity.py',
     '        return (str(catalog_number).strip().lower()\n                == str(labelled_number).strip().lower())',
     '        return left.index == right.index and left.suffix == right.suffix'),
    ('bridge: the asterisk stops mattering',
     'resolve/identity.py',
     '        return (a.index == b.index and a.suffix.lower() == b.suffix.lower()\n                and a.starred == b.starred)',
     '        return (a.index == b.index and a.suffix.lower() == b.suffix.lower()\n                and True)'),
    ('bridge: printed is rewritten around a supplied total',
     'resolve/identity.py',
     '    if parsed.total is not None:',
     '    if False:'),
    ('variants: the vocabulary goes flat again',
     'resolve/identity.py',
     '    if game is None:\n        return VARIANTS\n    return tuple(dict.fromkeys(SHARED_VARIANTS + GAME_VARIANTS.get(game, ())))',
     '    return VARIANTS'),
    ('variants: the rejection stops naming the other game',
     'resolve/identity.py',
     '    elsewhere = sorted(other for other, tokens in GAME_VARIANTS.items()\n                       if text in tokens and other != game)',
     '    elsewhere = []'),
    ('variants: numbered parallels ignore the game',
     'resolve/identity.py',
     '    return (stem in _NUMBERED_VARIANTS and stem in allowed and stem != text',
     '    return (stem in _NUMBERED_VARIANTS and stem != text'),
    ('ingest: the variant check drops the game',
     'resolve/label_cli.py',
     '        if row.get("variant") and not is_variant(row["variant"],\n                                                 row.get("game")):',
     '        if row.get("variant") and not is_variant(row["variant"]):'),
    ('set totals: `total` read instead of `official`',
     'ingest/catalog_sources.py',
     '            official = (counts.get("official") if isinstance(counts, dict)\n                        else None)',
     '            official = (counts.get("total") if isinstance(counts, dict)\n                        else None)'),
    ('set totals: a missing count is defaulted',
     'ingest/catalog_sources.py',
     '            if code and isinstance(official, int) and official > 0:',
     '            if code:\n                official = official or 1'),
    ('hard cases: C6 folded into the nearest kind',
     'resolve/hard_cases.py',
     '        "kind": "same_printed_number_different_treatment",',
     '        "kind": "alt_art_variant",'),
    ('hard cases: an unmappable class is silently dropped',
     'resolve/hard_cases.py',
     '        elif entry["kind"] is None:\n            unmapped.append(name)',
     '        elif entry["kind"] is None:\n            pass'),
    ('hard cases: an unknown class is silently dropped',
     'resolve/hard_cases.py',
     '        if entry is None:\n            unmapped.append(name)',
     '        if entry is None:\n            pass'),
    ('hard cases: the plural field is ignored',
     'resolve/hard_cases.py',
     '    for value in (card.get("hard_cases") or []):',
     '    for value in ():'),
    ('hard cases: the legacy single field is ignored',
     'resolve/hard_cases.py',
     '    single = card.get("hard_case")',
     '    single = None'),
    ('hard cases: classes are not split on the comma',
     'resolve/hard_cases.py',
     '    return tuple(part.strip() for part in raw.split(",") if part.strip())',
     '    return (raw,) if raw else ()'),
    ('gate: hard cases counted singly again',
     'tests/test_resolver_gate.py',
     '        kinds = {k for c in self.cards for k in hard_cases_of(c)}',
     '        kinds = {c.get("hard_case") for c in self.cards if c.get("hard_case")}'),
    ('hard cases: a re-tag leaves the old kind behind',
     'resolve/label_cli.py',
     '        if tuple(kinds) != before or shape != card.get("reprint_shape"):\n            card["hard_cases"] = list(kinds)',
     '        if tuple(kinds) != before or shape != card.get("reprint_shape"):\n            card["hard_cases"] = list(before) + [k for k in kinds if k not in before]'),
    ('gate: C6 is not required',
     'tests/test_resolver_gate.py',
     '                         "same_printed_number_different_treatment",',
     '                         '),
    ('reprint shape: the narrower kind is never added',
     'resolve/hard_cases.py',
     '        narrower = shape.get("kind")',
     '        narrower = None'),
    ('reprint shape: every pair reads as the same shape',
     'resolve/hard_cases.py',
     '    shape = card.get("reprint_shape")\n    return shape if shape in REPRINT_SHAPES else None',
     '    return "same_number_new_set" if card.get("pair_id") else None'),
    ('reprint shape: the pair tag is not read',
     'resolve/hard_cases.py',
     '    return card.get("pair_id") or None',
     '    return None'),
    ('CN-S becomes a derivable set code',
     'resolve/identity.py',
     'DERIVED_SET_CODE_LANGUAGES = frozenset(SET_CODE_SUFFIX)',
     'DERIVED_SET_CODE_LANGUAGES = frozenset({"CN-T", "CN-S"})'),
    ('One Piece reprints get new numbers',
     'resolve/identity.py',
     'REPRINTS_KEEP_THEIR_NUMBER = frozenset({"optcg"})',
     'REPRINTS_KEEP_THEIR_NUMBER = frozenset()'),
    ('gate: same_number_different_product is not required',
     'tests/test_resolver_gate.py',
     '                         "same_number_different_product",',
     '                         '),
    ('cross-language: the name check is not run',
     'resolve/identity.py',
     '        if not shares_numbering_across_languages(game):\n            continue',
     '        if True:\n            continue'),
    ('cross-language: applied to Pokemon too',
     'resolve/identity.py',
     'SHARED_NUMBERING_GAMES = frozenset({"optcg"})',
     'SHARED_NUMBERING_GAMES = frozenset({"optcg", "pkmn"})'),
    ('cross-language: cross-script pairs are compared',
     'resolve/identity.py',
     '        if not is_latin_name(card.get("name")):\n            continue',
     '        if False:\n            continue'),
    ('cross-language: punctuation splits one name in two',
     'resolve/identity.py',
     '    return "".join(ch for ch in str(name or "").lower() if ch.isalnum())',
     '    return str(name or "").lower()'),
    ('number forms: the prefixed-with-total form is unreadable again',
     'resolve/identity.py',
     '    hit = _NUM_PREFIXED_TOTAL.match(raw)',
     '    hit = None if True else _NUM_PREFIXED_TOTAL.match(raw)'),
    ('number forms: the prefix is discarded again',
     'resolve/identity.py',
     '                               prefix=raw.split("-", 1)[0].upper())',
     '                               prefix="")'),
    ('number forms: a different set reconciles anyway',
     'resolve/identity.py',
     '        if printed.prefix and printed.prefix != bare.prefix:\n            return False',
     '        if False:\n            return False'),
    ('upgrade: any confidence can be promoted',
     'resolve/label_cli.py',
     'UPGRADE_PATH = {("single_source", "verified")}',
     'UPGRADE_PATH = {("single_source", "verified"), ("verified", "verified"),\n                ("in_repo", "verified"), ("unstated", "verified")}'),
    ('upgrade: the second source is optional',
     'resolve/label_cli.py',
     '    if not second_source:',
     '    if False:'),
    ('interval: the one shared bisection is inverted',
     'audit/interval.py',
     '        if binomial_tail(n, at_least, mid) > alpha:\n            hi = mid\n        else:\n            lo = mid',
     '        if binomial_tail(n, at_least, mid) > alpha:\n            lo = mid\n        else:\n            hi = mid'),
    ('interval: the duality is replaced by a second implementation',
     'audit/interval.py',
     '    return 1.0 - clopper_pearson_lower(n, n - failures, alpha)',
     '    return _root(n, failures, alpha)'),
    ('interval: the gate re-implements the bound instead of adapting',
     'tests/test_resolver_gate.py',
     '        return clopper_pearson_lower(n, n - errors)',
     '        return 0.05 ** (1.0 / n) if n > 0 else 0.0'),
    ('interval: the exemption marker scan stops walking the comment block',
     'audit/checks/interval_properties.py',
     '                offset = child.lineno - 2          # 0-based, line above `def`',
     '                offset = child.lineno - 1'),
    ('interval: the clean-sweep bound is used as the gate',
     'tests/test_resolver_gate.py',
     '        one_error = self._lower_bound(n, errors=1)\n        self.assertLess(\n            one_error, threshold,',
     '        one_error = self._lower_bound(n, errors=0)\n        self.assertLess(\n            one_error, threshold,'),
    ('reprint shape: an unknown shape value is accepted',
     'resolve/hard_cases.py',
     '    return shape if shape in REPRINT_SHAPES else None',
     '    return shape'),
    ('gate: the fourth shape is not required',
     'tests/test_resolver_gate.py',
     '                         "same_number_new_set_new_variant"):',
     '                         ):'),
    ('C6 widened to absorb the fourth shape',
     'resolve/hard_cases.py',
     '        "kind": "same_number_new_set_new_variant",',
     '        "kind": "same_printed_number_different_treatment",'),
    ('status line counts the pool instead of ground truth',
     'resolve/label_cli.py',
     '    scored = [c for c in cards if c.get("confidence") in SCORED]\n    return (f"{\'COMPLETE\' if len(scored) >= TARGET_TOTAL else \'INCOMPLETE\'} -- "',
     '    scored = list(cards)\n    return (f"{\'COMPLETE\' if len(scored) >= TARGET_TOTAL else \'INCOMPLETE\'} -- "'),
    ('seal: a wrong count passes',
     'audit/mutate.py',
     '    if discovered != expected:',
     '    if False:'),
    ('seal: an unreadable seal passes',
     'audit/mutate.py',
     '        print(f"SEAL UNREADABLE: {SEAL} ({exc}). A missing seal is a failure, "\n              "not a pass -- it is exactly what a deleted catalogue looks "\n              "like.")\n        return False',
     '        return True'),
    ('seal: no run checks it',
     'audit/mutate.py',
     '    if not check_seal(len(MUTANTS)):\n        return 1',
     '    if False:\n        return 1'),
    ('seal: a filtered run is exempt from it again',
     'audit/mutate.py',
     '    if not check_seal(len(MUTANTS)):',
     '    if args.only or not check_seal(len(MUTANTS)):'),
    ('harness: the anchor check follows the filter',
     'audit/mutate.py',
     '    dirty = verify_tree(MUTANTS)\n    print(',
     '    dirty = verify_tree(wanted)\n    print('),
    ('corroboration: an unknown tier is assumed to be the strongest one',
     'resolve/corroboration.py',
     '    return bool(TIERS.get(tier, {}).get("counts_toward_verified", False))',
     '    return bool(TIERS.get(tier, {}).get("counts_toward_verified", True))'),
    ('corroboration: number-only counts toward verified',
     'resolve/corroboration.py',
     '        "counts_toward_verified": False,\n        "why": "A row whose second source is number-only',
     '        "counts_toward_verified": True,\n        "why": "A row whose second source is number-only'),
    ('corroboration: the retained-number reprint is no longer structural',
     'resolve/corroboration.py',
     '    "retained_number_reprint": {',
     '    "_retained_number_reprint": {'),
    ('corroboration: the discriminating source is not named',
     'resolve/corroboration.py',
     '        "discriminating_source": "Limitless serves a separate variant page per ',
     '        "_discriminating_source": "Limitless serves a separate variant page per '),
    ('limitless: the product is read off the title again',
     'ingest/limitless.py',
     '    for href, text in anchors(page):\n        slug = _SET_SLUG.search(href)\n        if not slug:\n            continue',
     '    for href, text in [("/cards/x-y", _text(page))] + anchors(page):\n        slug = _SET_SLUG.search(href)\n        if not slug:\n            continue'),
    ('limitless: the set code comes from the link text, not the href',
     'ingest/limitless.py',
     '        set_code = slug_text.split("-")[0]',
     '        set_code = shape.group("code")'),
    ('limitless: a slug disagreeing with its text is accepted',
     'ingest/limitless.py',
     '        if set_code.lower() != stated.lower():',
     '        if False:'),
    ('limitless: a page with no product link attests one anyway',
     'ingest/limitless.py',
     '    attested = parsed["set_code"] is not None',
     '    attested = True'),
    ('limitless: the tier is asserted without an attestation',
     'ingest/limitless.py',
     '        "corroboration_tier": "full" if attested else None,',
     '        "corroboration_tier": "full",'),
    ('limitless: the card-level reprint line is read as this variant',
     'ingest/limitless.py',
     '        "set_code": line["set_code"] if line else None,',
     '        "set_code": (reprint_note(page) or {}).get("product_code") or (line["set_code"] if line else None),'),
    ('limitless: the reprint line loses its card scope',
     'ingest/limitless.py',
     '            "scope": "card",',
     '            "scope": "variant",'),
    ('limitless: an unresolved product falls back to the page own product',
     'ingest/limitless.py',
     '            "product_set_code": known["set_code"] if known else None,',
     '            "product_set_code": (known["set_code"] if known\n                                 else parsed["set_code"]),'),
    ('limitless: the refusal on an unresolved slot is silent',
     'ingest/limitless.py',
     '            "unresolved": None if known else',
     '            "unresolved": None if True else'),
    ('limitless: the product index accepts label text, not just slugs',
     'ingest/limitless.py',
     '        line = product_line(page)\n        if line:\n            index.setdefault(line["product_name"].lower(),',
     '        line = product_line(page)\n        for row in print_table(page):\n            index.setdefault(split_label(row["label"])[0].lower(),\n                             {"set_code": "op01", "slug": "guessed"})\n        if line:\n            index.setdefault(line["product_name"].lower(),'),
    ('limitless: an image with no _pN is called slot 1',
     'ingest/limitless.py',
     '    return {"slot": int(slot) if slot is not None else None,',
     '    return {"slot": int(slot) if slot is not None else 1,'),
    ('limitless: an unreachable card is recorded as having no printings',
     'ingest/limitless.py',
     '            failures.append({"set_code": set_code, "number": number,\n                             "why": str(exc)[:300]})\n            continue',
     '            continue'),
    ('limitless: every slot is refetched, not just the unresolved ones',
     'ingest/limitless.py',
     '        if entry["product_set_code"]:\n            continue',
     '        if False:\n            continue'),
    ('slot: the response is trusted to be what was requested',
     'ingest/limitless.py',
     '        if not check["ok"]:\n            entry["unresolved"] = (\n                f"requested ?v={slot}; the page that came back is not it "',
     '        if False:\n            entry["unresolved"] = (\n                f"requested ?v={slot}; the page that came back is not it "'),
    ('slot: the card page is not verified before it is used',
     'ingest/limitless.py',
     '        check = verify_slot(page, None)',
     '        check = {"ok": True, "observed": None, "why": None}'),
    ('slot: a mismatch is credited to the slot that was asked for',
     'ingest/limitless.py',
     '    if got != wanted:',
     '    if False:'),
    ('signal3: the self-reference reports the request, not what was served',
     'ingest/limitless.py',
     '        "self_reference_links": {\n            "slot": self_ref["slot"] if self_ref["agreed"] else None,',
     '        "self_reference_links": {\n            "slot": None,'),
    ('signal3: language links disagreeing is resolved by majority',
     'ingest/limitless.py',
     '    if len(slots) > 1:\n        return {"slot": None, "references": seen, "agreed": False,\n                "why": "the header and language links disagree',
     '    if False:\n        return {"slot": None, "references": seen, "agreed": False,\n                "why": "the header and language links disagree'),
    ('signal3: self-references naming different cards are accepted',
     'ingest/limitless.py',
     '    if len(numbers) > 1:',
     '    if False:'),
    ('signal3: every bare link votes, print rows included',
     'ingest/limitless.py',
     '    voters = [ref for ref in seen\n              if ref["language"]\n              or (BASE_SLOT if ref["slot"] is None else ref["slot"]) in shared]',
     '    voters = list(seen)'),
    ('signal3: a page with nothing to distinguish a self-link is trusted',
     'ingest/limitless.py',
     '    if not voters:\n        return {"slot": None, "references": seen, "agreed": False,\n                "why": "no language-prefixed self-link',
     '    if False:\n        return {"slot": None, "references": seen, "agreed": False,\n                "why": "no language-prefixed self-link'),
    ('signal3: the base printing is not counted in the multiplicity',
     'ingest/limitless.py',
     '        key = BASE_SLOT if slot is None else int(slot)\n        counts[key] = counts.get(key, 0) + 1',
     '        if slot is None:\n            continue\n        key = int(slot)\n        counts[key] = counts.get(key, 0) + 1'),
    ('game: another game is served instead of refused',
     'ingest/limitless.py',
     '    if game != SERVES_GAME:',
     '    if False:'),
    ('game: a number that can never match is requested anyway',
     'ingest/limitless.py',
     '    if number is not None and not _OPTCG_NUMBER.match(str(number)):',
     '    if False:'),
    ('game: the card page skips the entry refusal',
     'ingest/limitless.py',
     '        refuse_other_games(self.game, number)\n        index = str(number)',
     '        index = str(number)'),
    ('game: attest skips the entry refusal',
     'ingest/limitless.py',
     '    refuse_other_games(game)\n    adapter = adapter or LimitlessAdapter()',
     '    adapter = adapter or LimitlessAdapter()'),
    ('signal3: the header link is counted as a printing',
     'ingest/limitless.py',
     '        if reference and (reference.group("language")\n                          or int(slot.group(1)) in skip):',
     '        if False:'),
    ('signal3: multiplicity is ignored, so every self-link is a print row',
     'ingest/limitless.py',
     '    return {slot for slot, count in counts.items() if count > 1}',
     '    return set()'),
    ('signal2: the body img is preferred over the head meta',
     'ingest/limitless.py',
     '    meta = meta_tags(page)\n    for key in IMAGE_META_KEYS:',
     '    meta = {}\n    for key in IMAGE_META_KEYS:'),
    ('signal2: the image source is not reported',
     'ingest/limitless.py',
     '            "source": source,',
     '            "source": "og:image",'),
    ('og:title: a product NAME is turned into a code when no slug is found',
     'ingest/limitless.py',
     '        return {"set_code": set_code.lower(), "stated_code": stated,\n                "product_name": shape.group("name").strip(" -\u2013\u2014\u00b7\u2022"),\n                "treatment": treatment, "slug": slug_text}\n    return None',
     '        return {"set_code": set_code.lower(), "stated_code": stated,\n                "product_name": shape.group("name").strip(" -\u2013\u2014\u00b7\u2022"),\n                "treatment": treatment, "slug": slug_text}\n    name = og_title_product_name(page)\n    if name:\n        return {"set_code": name.lower().replace(" ", "")[:5], "stated_code": name,\n                "product_name": name, "treatment": None, "slug": "from-og-title"}\n    return None'),
    ('slot: disagreeing signals pick one instead of refusing',
     'ingest/limitless.py',
     '    if len(distinct) > 1:\n        return {"slot": None, "agreed": False, "signals": signals,',
     '    if False:\n        return {"slot": None, "agreed": False, "signals": signals,'),
    ('slot: a page with no signal at all is treated as identified',
     'ingest/limitless.py',
     '    if not voted:\n        return {"slot": None, "agreed": False, "signals": signals,',
     '    if False:\n        return {"slot": None, "agreed": False, "signals": signals,'),
    ('slot: a complete run is read as base instead of abstaining',
     'ingest/limitless.py',
     '        return {"linked": linked, "unlinked_slot": None,\n                "unlinked_label": label,\n                "why": f"run 1..{max(slots)} is complete',
     '        return {"linked": linked, "unlinked_slot": "base",\n                "unlinked_label": label,\n                "why": f"run 1..{max(slots)} is complete'),
    ('slot: several missing slots still name a printing',
     'ingest/limitless.py',
     '    if len(missing) > 1:',
     '    if False:'),
    ('slot: comments are parsed as page content',
     'ingest/limitless.py',
     '    return _COMMENT.sub(" ", page or "")',
     '    return page or ""'),
    ('binding: the ?v=N <-> _pN mapping is assumed rather than reconfirmed',
     'ingest/limitless.py',
     '    if from_image == wanted:',
     '    if True:'),
    ('binding: a contradiction is blamed on the card',
     'ingest/limitless.py',
     '                   "mapping, not about this card."}',
     '                   "mapping."}'),
    ('count: a lower bound is reported as an exact total',
     'ingest/limitless.py',
     '        return {"printing_count": base_and_links,\n                "printing_count_exact": False,\n                "printing_count_why": "AT LEAST -- the page does not identify "',
     '        return {"printing_count": base_and_links,\n                "printing_count_exact": True,\n                "printing_count_why": "AT LEAST -- the page does not identify "'),
    ('count: the current printing is never added back',
     'ingest/limitless.py',
     '    return {"printing_count": base_and_links + 1,',
     '    return {"printing_count": base_and_links,'),
    ('limitless: the page is cached to raw/ again',
     'ingest/limitless.py',
     '        # Deliberately NOT self.cache_raw(url, body). See the docstring.',
     '        self.cache_raw(url, body)'),
    ('limitless: nothing fetched renders as an empty success',
     'ingest/limitless.py',
     '    if not (attestations or entries or failures):\n        lines += ["Nothing was fetched."]',
     '    if False:\n        lines += ["Nothing was fetched."]'),
    ('admission: a physical card is treated as decisive about its number',
     'resolve/corroboration.py',
     '        "number": "optical",\n        "name": "optical",',
     '        "number": "decisive",\n        "name": "optical",'),
    ('admission: the documentary source starts attesting the printing',
     'resolve/corroboration.py',
     '        "printing_exists": None,\n        "language": None,\n        "treatment": None,\n        "number": "documentary",',
     '        "printing_exists": "documentary",\n        "language": None,\n        "treatment": None,\n        "number": "documentary",'),
    ('admission: the checksum becomes optional',
     'resolve/corroboration.py',
     '    if rule["requires_checksum"] and not checksum_passed:',
     '    if False:'),
    ('admission: one channel composes with itself',
     'resolve/corroboration.py',
     '    if len(set(speaking)) < 2:',
     '    if False:'),
    ('admission: any pair of channels composes',
     'resolve/corroboration.py',
     '    rule = composes(set(speaking))\n    if not rule:',
     '    rule = composes(set(speaking)) or {"requires_checksum": True, "why": ""}\n    if not rule:'),
    ('admission: a silent source is read as a weak one',
     'resolve/corroboration.py',
     '    speaking = [channel for channel in channels if channel]',
     '    speaking = [channel or "documentary" for channel in channels]'),
    ('admission: the name is promoted to an identity field',
     'resolve/corroboration.py',
     'IDENTITY_FIELDS = ("printing_exists", "language", "treatment", "number")',
     'IDENTITY_FIELDS = ("printing_exists", "language", "treatment", "number", "name")'),
    ('admission: the CN-S name gap is reported as closed',
     'resolve/corroboration.py',
     '        "name_attestation": None if name_ok else "optical_only",',
     '        "name_attestation": None,'),
    ('admission: a physical card row needs no provenance',
     'resolve/corroboration.py',
     '        if not row.get(field):\n            problems.append(f"missing {field!r}")',
     '        if False:\n            problems.append(f"missing {field!r}")'),
    ('admission: an unknown checksum name is accepted',
     'resolve/corroboration.py',
     '    if row.get("checksum") not in (None, *CHECKSUM):',
     '    if False:'),
    ('ingest: the class translation is left to a runbook again',
     'resolve/label_cli.py',
     '        if accepted and not args.dry_run and not args.no_map_classes:',
     '        if False:'),
    ('reading: a photograph is treated as a second channel',
     'resolve/corroboration.py',
     '        "number": "optical",\n        "name": "optical",\n        "set_code": None,',
     '        "number": "optical",\n        "name": "documentary",\n        "set_code": None,'),
    ('reading: two optical readings promote the field',
     'resolve/corroboration.py',
     '    frozenset({"optical", "documentary"}): {',
     '    frozenset({"optical", "optical"}): {"why": "", "requires_checksum": False},\n    frozenset({"optical", "documentary"}): {'),
    ('reading: the photographer and the reader collapse to one role',
     'resolve/corroboration.py',
     '        "roles": ("imaged_by", "read_by"),',
     '        "roles": ("read_by",),'),
    ('reading: the method-specific provenance is not required',
     'resolve/corroboration.py',
     '    for field in METHOD_PROVENANCE.get(method, ()):',
     '    for field in ():'),
    ('reading: an unknown reading method is accepted',
     'resolve/corroboration.py',
     '    if method is not None and method not in READING_METHODS:',
     '    if False:'),
    ('reading: a direct reading may claim a photographer',
     'resolve/corroboration.py',
     '    if method == "direct" and row.get("imaged_by"):',
     '    if False:'),
    ('reading: an unreferenced photograph is called re-checkable',
     'resolve/corroboration.py',
     '    return bool(row.get("image_ref"))',
     '    return True'),
    ('reading: a direct reading is called re-checkable',
     'resolve/corroboration.py',
     '        "re_checkable": False,\n        "why_not": "Nobody can go and look again.',
     '        "re_checkable": True,\n        "why_not": "Nobody can go and look again.'),
    ('reading: the illegible-glyph back door is not named',
     'resolve/corroboration.py',
     '    "why_it_is_forbidden": "That is a confirmation against a prior',
     '    "_why_it_is_forbidden": "That is a confirmation against a prior'),
    ('reader: a model is assumed to notice its own misreading',
     'resolve/corroboration.py',
     '        "failure_mode": "CONFIDENT SUBSTITUTION of a visually similar "\n                        "character. Not a visible stumble -- a clean, "\n                        "assured, wrong answer.",\n        "self_detecting": False,',
     '        "failure_mode": "CONFIDENT SUBSTITUTION of a visually similar "\n                        "character. Not a visible stumble -- a clean, "\n                        "assured, wrong answer.",\n        "self_detecting": True,'),
    ('reader: an unclassified reader is assumed reliable',
     'resolve/corroboration.py',
     '    return bool(profile and profile["self_detecting"] is True)',
     '    return bool(profile is None or profile["self_detecting"] is True)'),
    ('reader: a non-self-detecting reader may supply an unchecksummed field',
     'resolve/corroboration.py',
     '    if field not in UNCHECKSUMMED_FIELDS:',
     '    if True:'),
    ('reader: the name is treated as checksummed',
     'resolve/corroboration.py',
     'UNCHECKSUMMED_FIELDS = ("name",)',
     'UNCHECKSUMMED_FIELDS = ()'),
    ('reader: an unknown profile passes the entry check',
     'resolve/corroboration.py',
     '    if reader_profile not in READER_PROFILES:',
     '    if False:'),
    ('reader: the row does not check what the reader may supply',
     'resolve/corroboration.py',
     '    problems.extend(_reader_problems(row))',
     '    pass'),
    ('reader: an unresolved name is still read as supplied',
     'resolve/corroboration.py',
     '    supplies_name = (row.get("name")\n                     and row.get("name_attestation") != "unresolved")',
     '    supplies_name = bool(row.get("name"))'),
    ('reader: an unknown profile on a row is accepted',
     'resolve/corroboration.py',
     '    if profile not in READER_PROFILES:\n        return [f"unknown reader_reliability {profile!r}',
     '    if False:\n        return [f"unknown reader_reliability {profile!r}'),
    ('endpoint: the guessed index shape is tried before the observed one',
     'ingest/limitless.py',
     '        "https://onepiece.limitlesstcg.com/cards/{number}",\n        "https://limitlesstcg.com/cards/op/{number}",',
     '        "https://onepiece.limitlesstcg.com/cards/{set_code}/{index}",\n        "https://limitlesstcg.com/cards/op/{number}",'),
    ('tcgapi: the card name goes into the URL unencoded again',
     'ingest/adapters.py',
     '                    name=urllib.parse.quote(str(card["name"]), safe=""),',
     '                    name=str(card["name"]),'),
    ('reader: a non-native reader of a logographic script is self-detecting',
     'resolve/corroboration.py',
     '                        "LOAD-BEARING. A smudge is noticed; a wrong radical "\n                        "is not.",\n        "self_detecting": False,',
     '                        "LOAD-BEARING. A smudge is noticed; a wrong radical "\n                        "is not.",\n        "self_detecting": True,'),
    ('name: a derived name is not recorded as inert',
     'resolve/corroboration.py',
     '    "why_it_is_worse_than_an_absent_name": "It reports nothing BY "',
     '    "_why_it_is_worse_than_an_absent_name": "It reports nothing BY "'),
    ('coverage: a one-row number is counted as compared',
     'resolve/identity.py',
     '    comparable = {k: v for k, v in examined.items() if len(v) > 1}',
     '    comparable = dict(examined)'),
    ('coverage: rows skipped for having no Latin name are not counted',
     'resolve/identity.py',
     '        if not is_latin_name(card.get("name")):\n            skipped_no_latin += 1\n            continue',
     '        if not is_latin_name(card.get("name")):\n            continue'),
    ('coverage: the detector reports findings without what it examined',
     'resolve/identity.py',
     '        "examined_rows": sum(len(v) for v in examined.values()),',
     '        "examined_rows": 0,'),
    ('art: partial self-detection is read as a licence',
     'resolve/corroboration.py',
     '    return bool(profile and profile["self_detecting"] is True)',
     '    return bool(profile and profile["self_detecting"])'),
    ('art: a partial reader may supply the name on the label alone',
     'resolve/corroboration.py',
     '    if READER_PROFILES[reader_profile]["self_detecting"] == "partial":\n        return False, (',
     '    if False:\n        return False, ('),
    ('art: the printed name is shown to the art call',
     'resolve/corroboration.py',
     '    "withhold": ("number", "card_uid", "set_code", "printed_name",',
     '    "withhold": ("number", "card_uid", "set_code",'),
    ('art: an uncommitted call is accepted as blind',
     'resolve/corroboration.py',
     '    if not call.get("committed_before_checksum"):',
     '    if False:'),
    ('art: a disagreement admits a name anyway',
     'resolve/corroboration.py',
     '    if call.get("outcome") != "agrees":',
     '    if False:'),
    ('art: no documentary name is read as agreement',
     'resolve/corroboration.py',
     '    if not documentary_name:\n        return "disagrees"',
     '    if not documentary_name:\n        return "agrees"'),
    ('art: the contaminated session is allowed to call',
     'resolve/corroboration.py',
     '    "may_call": False,',
     '    "may_call": True,'),
    ('art: a call needs no distinct reader identity',
     'resolve/corroboration.py',
     '    if call.get("reader_instance") in (None, "", "Claude", "this_session"):',
     '    if False:'),
    ('art: a call attributed to this session is accepted',
     'resolve/corroboration.py',
     '    if call.get("reader_instance") in (None, "", "Claude", "this_session"):',
     '    if call.get("reader_instance") in (None, ""):'),
    ('art: a call need not declare a fresh session',
     'resolve/corroboration.py',
     '    if not call.get("fresh_session"):',
     '    if False:'),
    ('art: the abstention report starts gating again',
     'resolve/corroboration.py',
     '        "gates_anything": False,',
     '        "gates_anything": True,'),
    ('art: zero abstentions is reported without its detectable floor',
     'resolve/corroboration.py',
     '    elif abstained == 0 and floor is not None:',
     '    elif False:'),
    ('art: the detectable floor is asserted rather than computed',
     'resolve/corroboration.py',
     '    return 1 - alpha ** (1.0 / n)',
     '    return 0.05'),
    ('upgrade: any string is a valid second source again',
     'resolve/label_cli.py',
     '    ok, why = second_source_is_admissible(second_source, card)\n    if not ok:\n        return None, why',
     '    ok, why = second_source_is_admissible(second_source, card)\n    if False:\n        return None, why'),
    ('upgrade: an unclassified source is waved through as classified',
     'resolve/label_cli.py',
     '    if name not in FIELD_ATTESTATION:',
     '    if False:'),
    ('upgrade: a physical_card claim needs no provenance',
     'resolve/label_cli.py',
     '        well_formed, problems = physical_card_row_is_well_formed(card)\n        if not well_formed:',
     '        well_formed, problems = physical_card_row_is_well_formed(card)\n        if False:'),
    ('upgrade: the composite is not checked, only the provenance fields',
     'resolve/label_cli.py',
     '        if not found["verified"]:',
     '        if False:'),
    ('upgrade: a batch may edit the claim it promotes',
     'resolve/label_cli.py',
     '        if identity_edits:',
     '        if False:'),
    ('upgrade: a batch promotes from any rung',
     'resolve/label_cli.py',
     '        if (was, row.get("to", "verified")) not in UPGRADE_PATH:',
     '        if False:'),
    ('taxonomy: the two species are given the same remedy',
     'audit/defect_taxonomy.py',
     '        "remedy": "Prove something invokes it.",',
     '        "remedy": "Prove it can fail.",'),
    ('taxonomy: the orphaned remedy stops naming the decision point',
     'audit/defect_taxonomy.py',
     '        "test_shape": "A test AT THE DECISION POINT that the decision is "',
     '        "test_shape": "A test that the check itself is "'),
    ('taxonomy: an unknown defect name resolves to a species',
     'audit/defect_taxonomy.py',
     '    for entry in INSTANCES:\n        if entry["name"] == name:\n            return entry["species"]\n    return None',
     '    for entry in INSTANCES:\n        if entry["name"] == name:\n            return entry["species"]\n    return "inert"'),
    ('taxonomy: instances_of stops filtering by species',
     'audit/defect_taxonomy.py',
     '    return [entry for entry in INSTANCES if entry["species"] == species]',
     '    return list(INSTANCES)'),
    ('scope: the data guard goes back to tracked files only',
     'audit/checks/no_provider_data.py',
     '    paths = set(tracked_files())\n    out = subprocess.run(["git", "ls-files", "--others", "--exclude-standard"],',
     '    paths = set(tracked_files())\n    return sorted(paths)\n    out = subprocess.run(["git", "ls-files", "--others", "--exclude-standard"],'),
    ('scope: rule 1 starts flagging untracked data files',
     'audit/checks/no_provider_data.py',
     '    for f in tracked:\n        for pat in FORBIDDEN_PATH_PATTERNS:',
     '    for f in files:\n        for pat in FORBIDDEN_PATH_PATTERNS:'),
    ('sweep: a vacuous pass is reported as a pass',
     'audit/checks/sweep_ground_truth.py',
     '    return VACUOUS, ("the gate approved because the row declares no "',
     '    return PASS, ("the gate approved because the row declares no "'),
    ('sweep: an inadmissible recorded second source is accepted',
     'audit/checks/sweep_ground_truth.py',
     '        if not ok:\n            return FAIL, f"its recorded second source is inadmissible: {why}", evidence',
     '        if False:\n            return FAIL, f"its recorded second source is inadmissible: {why}", evidence'),
    ('reverify: the name is included in the blinded request',
     'audit/checks/reverification_sample.py',
     'BLINDED_FIELDS = ("game", "set_code", "number", "variant", "language")',
     'BLINDED_FIELDS = ("game", "set_code", "number", "variant", "language", "name")'),
    ('reverify: an abstention counts as agreement',
     'audit/checks/reverification_sample.py',
     '        if not returned:\n            verdict = "abstained"',
     '        if not returned:\n            verdict = "agrees"'),
    ('reverify: orthography counts as a disagreement',
     'audit/checks/reverification_sample.py',
     '        elif normalise_name(returned) == normalise_name(card.get("name")):',
     '        elif returned == card.get("name"):'),
    ('reverify: an empty comparison is rendered as a clean result',
     'audit/checks/reverification_sample.py',
     '    if not n:\n        lines += ["Nothing was compared, so nothing was measured.',
     '    if False:\n        lines += ["Nothing was compared, so nothing was measured.'),
    ('reverify: the report stops saying the estimate is a floor',
     'audit/checks/reverification_sample.py',
     '              "This is a FLOOR, not an unbiased estimate. See the "',
     '              "This is an estimate. See the "'),
    ('reverify: the draw stops being reproducible from the seed',
     'audit/checks/reverification_sample.py',
     '    rng = random.Random(seed)',
     '    rng = random.Random()'),
    ('catalog: an ambiguous pair is taken as a pair',
     'audit/checks/catalog_precision.py',
     '        elif len(matches) > 1 or (how == "set_and_name"\n                                  and rows_by_key[key] > 1):',
     '        elif False:'),
    ('catalog: an empty denominator is reported as perfect',
     'audit/checks/catalog_precision.py',
     '            "precision": (right / used) if used else None,',
     '            "precision": (right / used) if used else 1.0,'),
    ('catalog: the catalog uid is fed back to the resolver',
     'audit/checks/catalog_precision.py',
     '            entries.append({"source": source, "game": card.get("game"),',
     '            entries.append({"card_uid": card.get("card_uid"), "source": source, "game": card.get("game"),'),
    ('catalog: the join stops being set-scoped',
     'audit/checks/catalog_precision.py',
     '            (row.get("game"), row.get("language")), ()) if _same_set(e, row)]',
     '            (row.get("game"), row.get("language")), ())]'),
    ('interval: the pin table loses its error rows',
     'audit/checks/interval_properties.py',
     'ALPHA = 0.05\n#: How far a function may sit from a pin',
     'PINS = tuple(p for p in PINS if p[1] == 0)\nALPHA = 0.05\n#: How far a function may sit from a pin'),
    ('interval: discovery goes back to tracked files only',
     'audit/checks/interval_properties.py',
     '    if untracked.returncode == 0:',
     '    if False:'),
    ('interval: an uncovered estimator is not reported',
     'audit/checks/interval_properties.py',
     '    uncovered = sorted(set(found) - set(CONTRACTS) - set(exempt))',
     '    uncovered = []'),
    ('interval: a stale contract passes',
     'audit/checks/interval_properties.py',
     '    stale = sorted(set(CONTRACTS) - set(found))',
     '    stale = []'),
    ('interval: the declared orientation is taken on trust',
     'audit/checks/interval_properties.py',
     '        return value if lower else 1.0 - value',
     '        return value'),
    ('interval: the battery records nothing',
     'audit/checks/interval_properties.py',
     '            out.append(f"{key}: {message}")',
     '            pass'),
    ('interval: alpha is no longer probed',
     'audit/checks/interval_properties.py',
     '    if contract["alpha_param"]:',
     '    if False:'),
    ('interval: a crash is swallowed',
     'audit/checks/interval_properties.py',
     '            failures = [f"{key}: the battery raised {exc!r}"]',
     '            failures = []'),
    ('interval: the exemption seal is ignored',
     'audit/checks/interval_properties.py',
     '    if len(exempt) != EXPECTED_EXEMPTIONS:',
     '    if False:'),
    ('interval: the pins are no longer checked against the binomial',
     'audit/checks/interval_properties.py',
     '        if abs(got - ALPHA) > PIN_EQUATION_TOLERANCE:',
     '        if False:'),
    ('bridge: the totals are collected and never used',
     'ingest/catalog.py',
     '    catalog, number_bridge = bridge_numbers(catalog, set_totals)',
     '    number_bridge = {}'),
    ('bridge: a colliding rename is merged instead of refused',
     'ingest/catalog.py',
     '            if len(group) > 1 and len(names) > 1:',
     '            if False:'),
    ('bridge: a missing total bridges anyway',
     'ingest/catalog.py',
     '            if total in (None, ""):\n                counts["no_set_total"] += 1',
     '            if False:\n                counts["no_set_total"] += 1'),
    ('bridge: the set that lacks a total is not named',
     'ingest/catalog.py',
     '                missing.add(str(card.get("set_code")))',
     '                pass'),
    ('bridge: an unreadable number is not counted',
     'ingest/catalog.py',
     '                counts["unreadable"] += 1',
     '                pass'),
    ('bridge: the report never reaches the runner file',
     'ingest/catalog.py',
     '        "_number_bridge": number_bridge,',
     '        "_number_bridge": {},'),
    ('bridge: the catalog is rewritten in place',
     'ingest/catalog.py',
     '            rows.append((card, dict(card, number=printed, card_uid=uid)))',
     '            card.update(number=printed, card_uid=uid)\n            rows.append((card, card))'),
    ('resolver: the bridge fires even when the exact lookup matched',
     'resolve/resolver.py',
     '        if not pool:\n            pool, bridged_from, why_not = self._bridged_pool(',
     '        if True:\n            pool, bridged_from, why_not = self._bridged_pool('),
    ('resolver: a bridged match is reported as an ordinary one',
     'resolve/resolver.py',
     '        if bridged_from is not None:',
     '        if False:'),
    ('resolver: the bridge runs even with no totals configured',
     'resolve/resolver.py',
     '        if not self.set_totals:\n            return [], None, ""',
     '        if False:\n            return [], None, ""'),
    ('resolver: an unknown total is not distinguished from an unknown card',
     'resolve/resolver.py',
     '        if total in (None, ""):\n            return [], None, (',
     '        if False:\n            return [], None, ('),
    ('precision: the measurement resolves without the totals',
     'audit/checks/catalog_precision.py',
     '    resolver = Resolver(pool, set_totals=set_totals)',
     '    resolver = Resolver(pool)'),
    ('precision: the field join stops bridging',
     'audit/checks/catalog_precision.py',
     '                (set_totals or {}).get(e.get("language"), {}).get(\n                    e.get("set_code")))) for e in candidates]',
     '                None)) for e in candidates]'),
    ('suppression: CannotBridge answers instead of refusing',
     'audit/checks/catalog_precision.py',
     '    except CannotBridge:\n        return CANNOT_TELL',
     '    except CannotBridge:\n        return False'),
    ('suppression: could-not-tell is filed as a non-match',
     'audit/checks/catalog_precision.py',
     '        if not matches and how != "set_and_name" and undecided:',
     '        if False:'),
    ('suppression: a rate limit answers the filter probe',
     'ingest/catalog_sources.py',
     '        except RateLimited as exc:',
     '        except RateLimited as exc:\n            return FILTER_UNMEASURED'),
    ('suppression: an unmeasured probe is filed as a measured miss',
     'ingest/catalog_sources.py',
     '            if honoured is FILTER_UNMEASURED:',
     '            if False:'),
    ('suppression: the audit stops reading untracked files',
     'audit/checks/no_suppressed_refusal.py',
     '    if other.returncode == 0:',
     '    if False:'),
    ('suppression: a bare except is never in scope',
     'audit/checks/no_suppressed_refusal.py',
     '                if not named_refusal and not (catch_all and body_refuses):',
     '                if not named_refusal:'),
    ('suppression: False counts as nothing-known',
     'audit/checks/no_suppressed_refusal.py',
     '        return node.value is None or node.value == ""',
     '        return node.value is None or node.value == "" or node.value is False'),
    ('suppression: binding the exception is not required',
     'audit/checks/no_suppressed_refusal.py',
     '    if bound and any(_mentions(node, bound) for node in handler.body):',
     '    if True:'),
    ('suppression: a sentinel may be reassigned and still count',
     'audit/checks/no_suppressed_refusal.py',
     '            if (isinstance(target, ast.Name) and assigned.get(target.id) == 1',
     '            if (isinstance(target, ast.Name)'),
    ('oracle: the publisher id is read and dropped again',
     'ingest/catalog_sources.py',
     '           "external_id": str(find(hit, "id", "card_id") or ""),',
     '           "external_id": "",'),
    ('oracle: the illustrator does not reach the targets file',
     'ingest/catalog.py',
     '                "artist": hit.get("artist"),',
     '                "artist": None,'),
    ('oracle: rarity is withheld from the resolver',
     'audit/checks/catalog_precision.py',
     '                  "rarity": entry.get("rarity")}',
     '                  "rarity": None}'),
    ('oracle: external_id is fed to the resolver after all',
     'audit/checks/catalog_precision.py',
     '                  "set_code": entry["set_code"], "name": entry["name"],',
     '                  "set_code": entry["set_code"], "name": entry["name"],\n                  "external_id": entry.get("external_id"),'),
    ('headline: the point estimate is quoted without its n',
     'audit/checks/catalog_precision.py',
     '             "resolver\'s job.", "", headline(result), ""]',
     '             "resolver\'s job.", ""]'),
    ('headline: the gate quotes its own figure alone',
     'tests/test_resolver_gate.py',
     '            + HONEST_HEADLINE)',
     '            )'),
    ('apitcg: fetch goes back to one request per card',
     'ingest/adapters.py',
     '            if game not in indexes:',
     '            if False:'),
    ('apitcg: the per-card fallback has no ceiling',
     'ingest/adapters.py',
     '            if fallbacks >= self.MAX_PER_CARD_FALLBACK:\n                continue',
     '            if False:\n                continue'),
    ('apitcg: a sweep miss is not counted',
     'ingest/adapters.py',
     '            self.uncovered_by_sweep += 1',
     '            pass'),
    ('apitcg: the sweep stops after the first page',
     'ingest/adapters.py',
     '            if not rows or seen >= int(total or 0) or page > 100:',
     '            if True:'),
    ('harness: a dirty tree still produces a baseline',
     'audit/mutate.py',
     '    dirty = verify_tree(MUTANTS)',
     '    dirty = []'),
    ('harness: SIGTERM no longer restores the file',
     'audit/mutate.py',
     '    for name in ("SIGTERM", "SIGHUP"):',
     '    for name in ():'),
    ('report: the amplification column is not computed',
     'ingest/runner.py',
     '        if batched and calls > batched:',
     '        if False:'),
    ('report: the target count never reaches the result',
     'ingest/runner.py',
     '            "targets": _target_count(targets),',
     '            "targets": 0,'),
    ('report: the batch size is not read from the adapter',
     'ingest/runner.py',
     '        "cards_per_request": getattr(adapter, "cards_per_request", 1),',
     '        "cards_per_request": 1,'),
    ('report: apitcg no longer declares its batched form',
     'ingest/adapters.py',
     '    cards_per_request = PAGE_SIZE',
     '    cards_per_request = 1'),
    ('report: the preflight key column is always unknown',
     'ingest/runner.py',
     '                    key, state = "n/a", "ready (no key required)"',
     '                    state = "ready (no key required)"'),
    ('headline: the pin stops tracking the measurement',
     'tests/test_resolver_gate.py',
     '        self.assertEqual(\n            best["used"], HEADLINE_N,',
     '        self.assertEqual(\n            best["used"], best["used"],'),
]
