"""Every mutant this project has been verified against.

One catalogue, in the repository, so "all mutations caught" is a claim anyone
can re-run instead of one they have to take on trust. Each entry is
(label, path, original, mutated) and the original must still appear in the
file -- `audit/mutate.py` reports a stale anchor as a FAILURE, because a mutant
whose anchor has drifted is a guard that has silently stopped testing anything.

`tests/test_labelled_ingest.py` asserts every anchor still matches, which is
the cheap half of a mutation run: it executes nothing and catches drift the
moment it happens.
"""

MUTANTS = [
    ('set code: brief derivation removed',
     'ingest/catalog_sources.py',
     '    ident = str(find(hit, "id") or "")',
     '    return ""\n    ident = str(find(hit, "id") or "")'),
    ('set code: split on the FIRST hyphen',
     'ingest/catalog_sources.py',
     '        return ident.rsplit("-", 1)[0]',
     '        return ident.split("-", 1)[0]'),
    ('set code: localId suffix ignored',
     'ingest/catalog_sources.py',
     '    if ident and local and ident.endswith(f"-{local}"):',
     '    if False:'),
    ('dropped rows not counted',
     'ingest/catalog_sources.py',
     '                self.dropped_no_identity += 1',
     '                pass'),
    ('sealed: a missing type field means not-a-card',
     'ingest/catalog.py',
     '    if not present:\n        return False',
     '    if not present:\n        return True'),
    ('sealed: rarity no longer has to be absent',
     'ingest/catalog.py',
     '    return (all(hit[k] in (None, "") for k in present)\n            and hit.get("rarity") in (None, ""))',
     '    return all(hit[k] in (None, "") for k in present)'),
    ('sealed: the drop is silent',
     'ingest/catalog.py',
     '            self.note_not_a_card(game, language, number, find(hit, "name"))',
     '            pass'),
    ('set size: aliases ignored',
     'ingest/catalog.py',
     '        code = RIFTBOUND_SET_ALIASES.get(key.lower(), key.upper())',
     '        code = key.upper()'),
    ('unreadable number: sample not kept',
     'ingest/catalog.py',
     '            self.note_unbandable(game, language, rarity, number)',
     '            pass'),
    ('unreadable number: banded base instead of unknown',
     'ingest/rarity.py',
     '    if parsed.kind == "unreadable":',
     '    if False:'),
    ('deliberate unknowns are treated as unclassified',
     'ingest/rarity.py',
     '    return _BY_GAME.get(game, {}).get(normalise(rarity)) == UNKNOWN',
     '    return False'),
    ('429: breaker never trips',
     'ingest/base.py',
     '        elif self.rate_limit_hits >= self.stop_calling_after_rate_limits:',
     '        elif False:'),
    ('429: a closed adapter keeps calling',
     'ingest/base.py',
     '            if self.rate_limited:\n                raise RateLimited(',
     '            if False:\n                raise RateLimited('),
    ('429: Retry-After ignored',
     'ingest/base.py',
     '                              seconds=retry_after_seconds(response_headers))',
     '                              seconds=None)'),
    ('429: an hour-long Retry-After is honoured',
     'ingest/base.py',
     '        if wait is not None and wait > self.max_retry_after_seconds:',
     '        if False:'),
    ('Retry-After: only the integer form is read',
     'ingest/base.py',
     '            when = email.utils.parsedate_to_datetime(text)',
     '            when = None'),
    ('rate headers: not kept',
     'ingest/base.py',
     '            self.rate_headers.update(found)',
     '            pass'),
    ('cache: an undated entry counts as fresh',
     'ingest/catalog.py',
     '    if not stamp:\n        return None',
     '    if not stamp:\n        return 0.0'),
    ('cache: --force does not force',
     'ingest/catalog.py',
     '            if fresh and not force:',
     '            if fresh:'),
    ('cache: a cached combo reads as ok',
     'ingest/catalog.py',
     '                    "status": "catalog_from_cache", "cards": len(cards),',
     '                    "status": "ok", "cards": len(cards),'),
    ('cache: a failed refresh does not fall back',
     'ingest/catalog.py',
     '            elif cached.get("cards"):',
     '            elif False:'),
    ('cache: a cached combo is restamped with today',
     'ingest/catalog.py',
     '            as_of = (cache.get(combo) or {}).get("as_of")',
     '            as_of = entry.get("as_of")'),
    ('cache: an empty combo is stamped anyway',
     'ingest/catalog.py',
     '        if not cards:\n            # Nothing to remember.',
     '        if False:\n            # Nothing to remember.'),
    ('persist: zero cards accepted',
     'ingest/catalog.py',
     '    if total <= 0:',
     '    if False:'),
    ('persist: undated cards accepted',
     'ingest/catalog.py',
     '    if undated:',
     '    if False:'),
    ('fallback: serving reads as plain ok',
     'ingest/catalog.py',
     '            if deduped and primary and primary not in sources:',
     '            if False:'),
    ('429: a refused combo is called unreachable',
     'ingest/catalog.py',
     '                kind = ("apitcg_rate_limited" if isinstance(exc, RateLimited)',
     '                kind = ("apitcg_unreachable" if isinstance(exc, RateLimited)'),
    ('id suffix: parallels merge into base',
     'resolve/identity.py',
     '    match = _ID_SUFFIX.search(str(external_id or ""))',
     '    match = None'),
    ('id suffix: every parallel is the same token',
     'resolve/identity.py',
     '    return stem if index in ("", "1") else f"{stem}{index}"',
     '    return stem'),
    ('id suffix: an unknown suffix becomes base',
     'resolve/identity.py',
     '        return "unknown_" + match.group(1).lower() + match.group(2)',
     '        return None'),
    ('id suffix: applied to every game',
     'resolve/identity.py',
     '    if game is not None and game not in ID_SUFFIX_VARIANT_GAMES:\n        return None\n    match = _ID_SUFFIX',
     '    match = _ID_SUFFIX'),
    ('id suffix: loses to the rarity string',
     'ingest/catalog.py',
     '        variant = (variant_from_number(number, size, game)\n                   or variant_from_external_id(external_id, game)\n                   or _variant_of(rarity, name, language, game))',
     '        variant = (variant_from_number(number, size, game)\n                   or _variant_of(rarity, name, language, game)\n                   or variant_from_external_id(external_id, game))'),
    ('cache state: absent and empty collapse',
     'ingest/catalog.py',
     '    if not cached:\n        return "absent"',
     '    if not cached:\n        return "empty"'),
    ('cache state: undated reads as stale',
     'ingest/catalog.py',
     '    if age is None:\n        return "undated"',
     '    if age is None:\n        return "stale"'),
    ('cache state: --force reads as an ordinary refresh',
     'ingest/catalog.py',
     '    return "forced" if force else "fresh"',
     '    return "fresh"'),
    ('cache state: the threshold boundary flips',
     'ingest/catalog.py',
     '    if age >= max_age_days:\n        return "stale"',
     '    if age > max_age_days:\n        return "stale"'),
    ('cache state: not recorded on a re-enumerated combo',
     'ingest/catalog.py',
     '                "cache_state": state,\n                "age_days": None if age is None else round(age, 2),',
     '                "age_days": None if age is None else round(age, 2),'),
    ('the fresh-but-refreshed fault is not reported',
     'ingest/catalog.py',
     '    return (entry.get("cache_state") == "fresh"\n            and not str(entry.get("status", "")).startswith("catalog_from_cache"))',
     '    return False'),
    ('--force is reported as the fault',
     'ingest/catalog.py',
     '    return (entry.get("cache_state") == "fresh"',
     '    return (entry.get("cache_state") in ("fresh", "forced")'),
    ('preserve: an empty combo is committed over yesterday',
     'ingest/catalog.py',
     '    for combo, entry in sorted((previous or {}).items()):',
     '    for combo, entry in sorted({}.items()):'),
    ('preserve: a combo that shrank is resurrected',
     'ingest/catalog.py',
     '        if (catalog.get(combo) or {}).get("cards"):\n            continue',
     '        if False:\n            continue'),
    ('preserve: the reason it was empty is dropped',
     'ingest/catalog.py',
     '            "preserved_over": (combo_status.get(combo) or {}).get("status"),',
     '            "preserved_over": None,'),
    ('preserve: reads as plain ok',
     'ingest/catalog.py',
     '            "status": "catalog_from_cache_preserved",',
     '            "status": "ok",'),
    ('--no-cache erases instead of preserving',
     'ingest/catalog.py',
     '    previous = load_cached_catalog(args.out)\n    cache = {} if args.no_cache else previous',
     '    cache = {} if args.no_cache else load_cached_catalog(args.out)\n    previous = cache'),
    ('to_targets stamps from the freshness cache',
     'ingest/catalog.py',
     '                         builder.not_a_card, cache=previous,\n                         set_totals=builder.set_totals)',
     '                         builder.not_a_card, cache=cache,\n                         set_totals=builder.set_totals)'),
    ('persist step gated on the run succeeding',
     '.github/workflows/ingest.yml',
     "          always()\n          && steps.persist_check.outcome == 'success'",
     "          success()\n          && steps.persist_check.outcome == 'success'"),
    ('TC set code: F suffix not required',
     'resolve/identity.py',
     '    if len(code) <= len(suffix) or not code.lower().endswith(suffix.lower()):\n        return None',
     '    if False:\n        return None'),
    ('TC set code: comparison becomes case-sensitive',
     'resolve/identity.py',
     '    return parent.lower() == str(japanese_set_code or "").strip().lower()',
     '    return parent == str(japanese_set_code or "").strip()'),
    ("CN-S given CN-T's numbering behaviour",
     'resolve/identity.py',
     '    return language in NUMBERING_PARENT',
     '    return language in ("CN-T", "CN-S")'),
    ('confusable numbers: table ignored',
     'resolve/identity.py',
     '    entry = KNOWN_CONFUSABLE_NUMBERS.get((game, set_code, name))',
     '    entry = None'),
    ('ingest: confidence not required',
     'resolve/label_cli.py',
     'REQUIRED_FIELDS = ("card_uid", "game", "set_code", "number", "variant",\n                   "language", "name", "source", "confidence")',
     'REQUIRED_FIELDS = ("card_uid", "game", "set_code", "number", "variant",\n                   "language", "name", "source")'),
    ('ingest: an unknown confidence is accepted',
     'resolve/label_cli.py',
     '        if row.get("confidence") and row["confidence"] not in CONFIDENCE:',
     '        if False:'),
    ('ingest: the stated uid is trusted',
     'resolve/label_cli.py',
     '                if row["card_uid"] != expected:',
     '                if False:'),
    ('ingest: an unknown variant is accepted',
     'resolve/label_cli.py',
     '        if row.get("variant") and not is_variant(row["variant"],\n                                                 row.get("game")):',
     '        if False:'),
    ('ingest: known confusables are accepted',
     'resolve/label_cli.py',
     '        if confusable and row.get("number") in confusable["confusable"]:',
     '        if False:'),
    ('ingest: rejected rows are written anyway',
     'resolve/label_cli.py',
     '        if why:\n            rejected.append({"index": index, "row": row, "why": why})\n        else:\n            accepted.append(row)',
     '        rejected.append({"index": index, "row": row, "why": why}) if False else None\n        accepted.append(row)'),
    ('ingest: dry run writes',
     'resolve/label_cli.py',
     '    if accepted and not dry_run:',
     '    if accepted:'),
    ('ingest: a duplicate is silently merged',
     'resolve/label_cli.py',
     '        if not why and row["card_uid"] in existing:',
     '        if False:'),
    ('single_source promoted to ground truth',
     'resolve/label_cli.py',
     'SCORED = ("verified",)',
     'SCORED = ("verified", "single_source")'),
    ('gate: scores every row, not just verified',
     'tests/test_resolver_gate.py',
     '    return [c for c in data["cards"] if c.get("confidence") in SCORED]',
     '    return list(data["cards"])'),
    ('gate: pool breakdown collapses',
     'tests/test_resolver_gate.py',
     '    return collections.Counter(c.get("confidence", "unstated")\n                               for c in data["cards"])',
     '    return collections.Counter({"unstated": len(data["cards"])})'),
    ('set alias: not applied',
     'resolve/identity.py',
     '    entry = SET_CODE_ALIASES.get((game, language, str(set_code or "")))',
     '    entry = None'),
    ('set alias: unknown codes rewritten instead of passed through',
     'resolve/identity.py',
     '    return (entry["code"], entry) if entry else (set_code, None)',
     '    return (entry["code"], entry) if entry else ("", None)'),
    ('set alias: uid not rebuilt after renaming',
     'resolve/label_cli.py',
     '            if row.get("card_uid"):\n                row["card_uid"] = ":".join(',
     '            if False:\n                row["card_uid"] = ":".join('),
    ('supersede: fires without the flag',
     'resolve/label_cli.py',
     '            if (supersede_unstated\n                    and previous.get("confidence") == "unstated"',
     '            if (True\n                    and previous.get("confidence") == "unstated"'),
    ('supersede: applies to a stated confidence too',
     'resolve/label_cli.py',
     '                    and previous.get("confidence") == "unstated"',
     '                    and previous.get("confidence") is not None'),
    ('supersede: the old row is not removed',
     'resolve/label_cli.py',
     '        kept = [c for c in labelled.get("cards", [])\n                if c["card_uid"] not in replaced]',
     '        kept = list(labelled.get("cards", []))'),
    ('supersede: annotations are dropped',
     'resolve/label_cli.py',
     '                inherited = {k: v for k, v in previous.items()\n                             if k not in row and k not in _NOT_INHERITED}',
     '                inherited = {}'),
    ('supersede: provenance is inherited too',
     'resolve/label_cli.py',
     '_NOT_INHERITED = frozenset({"confidence", "source", "verified_from",\n                            "supersedes", "supersedes_confidence",\n                            "inherited_fields", "adjudication"})',
     '_NOT_INHERITED = frozenset()'),
    ('supersede: no reference recorded',
     'resolve/label_cli.py',
     '                row.update(supersedes=previous.get("card_uid"),',
     '                row.update(supersedes=None,'),
    ('blocking-on-real-data: silently skips everything',
     'tests/test_resolver_gate.py',
     '        if len(present) < 2:',
     '        if True:'),
    ("blocking-on-real-data: a row may resolve to another's identity",
     'tests/test_resolver_gate.py',
     '        for uid, resolved in got.items():\n            self.assertEqual(\n                resolved, uid,',
     '        for uid, resolved in got.items():\n            self.assertIsNotNone(\n                resolved,'),
    ('bridge: an unknown total falls back to the index',
     'resolve/identity.py',
     '    if set_total in (None, ""):\n        raise CannotBridge(\n            f"{catalog_number!r} carries no denominator and the set\'s official "',
     '    if False:\n        raise CannotBridge(\n            f"{catalog_number!r} carries no denominator and the set\'s official "'),
    ('bridge: printed_from_bare defaults a missing total',
     'resolve/identity.py',
     '    if set_total in (None, ""):\n        raise CannotBridge(\n            f"cannot derive a printed number for {bare_number!r}: the set\'s "',
     '    if False:\n        raise CannotBridge(\n            f"cannot derive a printed number for {bare_number!r}: the set\'s "'),
    ('bridge: two naked indices are compared',
     'resolve/identity.py',
     '    if left.kind == "bare" and right.kind == "bare":',
     '    if False:'),
    ('bridge: the denominator stops mattering',
     'resolve/identity.py',
     '    return (bare.index == printed.index and int(set_total) == printed.total',
     '    return (bare.index == printed.index and True'),
    ('bridge: set-prefixed numbers compared by parsed index',
     'resolve/identity.py',
     '        return (str(catalog_number).strip().lower()\n                == str(labelled_number).strip().lower())',
     '        return left.index == right.index and left.suffix == right.suffix'),
    ('bridge: the asterisk stops mattering',
     'resolve/identity.py',
     '                and left.starred == right.starred)\n\n    # One side is bare.',
     '                and True)\n\n    # One side is bare.'),
    ('bridge: printed is rewritten around a supplied total',
     'resolve/identity.py',
     '    if parsed.total is not None:',
     '    if False:'),
    ('variants: the vocabulary goes flat again',
     'resolve/identity.py',
     '    if game is None:\n        return VARIANTS\n    return tuple(dict.fromkeys(SHARED_VARIANTS + GAME_VARIANTS.get(game, ())))',
     '    return VARIANTS'),
    ('variants: the rejection stops naming the other game',
     'resolve/identity.py',
     '    elsewhere = sorted(other for other, tokens in GAME_VARIANTS.items()\n                       if text in tokens and other != game)',
     '    elsewhere = []'),
    ('variants: numbered parallels ignore the game',
     'resolve/identity.py',
     '    return (stem in _NUMBERED_VARIANTS and stem in allowed and stem != text',
     '    return (stem in _NUMBERED_VARIANTS and stem != text'),
    ('ingest: the variant check drops the game',
     'resolve/label_cli.py',
     '        if row.get("variant") and not is_variant(row["variant"],\n                                                 row.get("game")):',
     '        if row.get("variant") and not is_variant(row["variant"]):'),
    ('set totals: `total` read instead of `official`',
     'ingest/catalog_sources.py',
     '            official = (counts.get("official") if isinstance(counts, dict)\n                        else None)',
     '            official = (counts.get("total") if isinstance(counts, dict)\n                        else None)'),
    ('set totals: a missing count is defaulted',
     'ingest/catalog_sources.py',
     '            if code and isinstance(official, int) and official > 0:',
     '            if code:\n                official = official or 1'),
    ('hard cases: C6 folded into the nearest kind',
     'resolve/hard_cases.py',
     '    "C6": {\n        "kind": None,',
     '    "C6": {\n        "kind": "alt_art_variant",'),
    ('hard cases: an unmappable class is silently dropped',
     'resolve/hard_cases.py',
     '        elif entry["kind"] is None:\n            unmapped.append(name)',
     '        elif entry["kind"] is None:\n            pass'),
    ('hard cases: an unknown class is silently dropped',
     'resolve/hard_cases.py',
     '        if entry is None:\n            unmapped.append(name)',
     '        if entry is None:\n            pass'),
    ('hard cases: the plural field is ignored',
     'resolve/hard_cases.py',
     '    for value in (card.get("hard_cases") or []):',
     '    for value in ():'),
    ('hard cases: the legacy single field is ignored',
     'resolve/hard_cases.py',
     '    single = card.get("hard_case")',
     '    single = None'),
    ('hard cases: classes are not split on the comma',
     'resolve/hard_cases.py',
     '    return tuple(part.strip() for part in raw.split(",") if part.strip())',
     '    return (raw,) if raw else ()'),
    ('gate: hard cases counted singly again',
     'tests/test_resolver_gate.py',
     '        kinds = {k for c in self.cards for k in hard_cases_of(c)}',
     '        kinds = {c.get("hard_case") for c in self.cards if c.get("hard_case")}'),
]
