#!/usr/bin/env python3
"""Cheap structural questions, asked before any card budget is spent.

Roughly three requests. It answers the things that can invalidate an entire
21-card run before it starts:

  * Does a One Piece Japan entry exist in tcgapi.dev's catalog?
  * What are the numeric game ids, and which combo maps to which?
  * Does apitcg.com expose a game list, and does it model language at all?

Run this first, then `coverage.py --smoke`, then the full probe.

Usage
-----
  python -m probe.structure               # live, ~3 requests
  python -m probe.structure --replay F    # against a fixture, zero network
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import types

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

from probe import coverage as cov  # noqa: E402

STRUCTURE_PATH = os.path.join(HERE, "STRUCTURE.md")

# apitcg.com does not document a game-list endpoint we could confirm from
# here, so these are candidates; a failure is reported, not guessed around.
APITCG_GAMES_ENDPOINTS = [
    "https://apitcg.com/api/games",
    "https://www.apitcg.com/api/games",
]


def probe_apitcg_games(prober):
    out = {"reached": False, "games": [], "status": 0, "note": ""}
    env = os.environ.get("APITCG_GAMES_URLS")
    cov.ENDPOINTS["apitcg.games"] = ([t.strip() for t in env.split(",") if t.strip()]
                                     if env else list(APITCG_GAMES_ENDPOINTS))
    payload, status, note = prober.call_ctx("apitcg.games", "apitcg.com", {}, "structure")
    out["status"], out["note"] = status, note
    if cov.classify_body(payload, status) not in (cov.BODY_OK, cov.BODY_EMPTY):
        return out
    out["reached"] = True
    entries = payload
    if isinstance(payload, dict):
        for k in cov.ENVELOPE_KEYS:
            if isinstance(payload.get(k), list):
                entries = payload[k]
                break
    if isinstance(entries, list):
        for e in entries:
            if isinstance(e, dict):
                out["games"].append(str(e.get("slug") or e.get("id") or e.get("name")))
            elif isinstance(e, str):
                out["games"].append(e)
    return out


def build_structure_report(games, apitcg, prober):
    L = []
    A = L.append
    A("# Catalog structure")
    A("")
    A(f"Generated by `probe/structure.py` at **{cov.now_iso()}**. Structural questions "
      "only -- no card lookups, no prices, a handful of requests.")
    A("")

    A("## tcgapi.dev")
    A("")
    if not games.get("reached"):
        A(f"**Not reached** -- HTTP {games.get('status') or '--'} "
          f"({games.get('body_class')}). {games.get('note') or ''}")
        A("")
    else:
        A(f"Read {games['pages']} page(s)"
          + (f" of {games['total']} games" if games.get("total") else "")
          + ("; list complete." if games.get("complete")
             else " -- **list incomplete**, so a missing game is not proof of absence."))
        A("")
        A("| Combo | Catalog game | id |")
        A("|---|---|---|")
        for game, lang, label in cov.COMBOS:
            m = (games.get("mapping") or {}).get(f"{game}:{lang}")
            A(f"| {label} | {m['name']} | `{m['id']}` |" if m
              else f"| {label} | **no entry** | -- |")
        A("")
        op_jp = (games.get("mapping") or {}).get("one-piece:JP")
        if op_jp:
            A(f"**Does a One Piece Japan entry exist?** Yes -- `{op_jp['name']}` "
              f"(id `{op_jp['id']}`).")
        elif games.get("complete"):
            A("**Does a One Piece Japan entry exist?** No. The game list was read in full "
              "and contains no Japanese One Piece entry, so tcgapi.dev cannot distinguish "
              "the Japanese printing -- One Piece JP has no automated raw price here.")
        else:
            A("**Does a One Piece Japan entry exist?** Unknown -- the game list was "
              "truncated, so absence is not established.")
        A("")
        A(f"**Language dimension:** {'yes' if games.get('language_dimension') else 'no'} -- "
          + ("language is modelled as separate game entries, so printings can be "
             "distinguished." if games.get("language_dimension") else
             "no per-language entries, so printings cannot be distinguished here."))
        A("")

    A("## apitcg.com")
    A("")
    if apitcg.get("reached"):
        A(f"Game list reachable, {len(apitcg['games'])} entries: "
          + ", ".join(f"`{g}`" for g in apitcg["games"][:40]) + ".")
        A("")
        langish = [g for g in apitcg["games"]
                   if any(t in g.lower() for t in cov.LANG_HINTS)]
        A(f"**Language dimension:** {'yes -- ' + ', '.join(langish) if langish else 'no'}. "
          + ("" if langish else
             "Every combo of a game resolves to the same slug, so apitcg.com cannot "
             "separate language printings and is an English-only second opinion."))
    else:
        A(f"**No game list reachable** -- HTTP {apitcg.get('status') or '--'}"
          f"{(': ' + apitcg['note']) if apitcg.get('note') else ''}. Falling back to the "
          "hardcoded hyphenated slugs.")
        A("")
        A("| Combo | apitcg.com `{game}` |")
        A("|---|---|")
        for game, lang, label in cov.COMBOS:
            A(f"| {label} | `{cov.APITCG_GAME.get(game, game)}` |")
    A("")

    A("## Cost")
    A("")
    A("| Provider | Requests | State |")
    A("|---|---|---|")
    for p in prober.providers.values():
        A(f"| {p.name} | {p.requests} | {p.status_note()} |")
    A("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description="cheap structural probe")
    ap.add_argument("--replay", metavar="FIXTURE", help="run against a fixture, zero network")
    ap.add_argument("--budget", type=int, default=int(os.environ.get("PROBE_BUDGET", "90")))
    ap.add_argument("--timeout", type=int, default=20)
    args = ap.parse_args()

    scenario = None
    if args.replay:
        with open(args.replay, encoding="utf-8") as f:
            scenario = json.load(f)

    ns = types.SimpleNamespace(offline=False, use_cache=False, replay=args.replay,
                               budget=args.budget, timeout=args.timeout)
    prober = cov.Prober(ns, scenario=scenario)
    prober.preflight()

    print("structure: tcgapi.dev /v1/games", file=sys.stderr)
    games = cov.probe_games(prober)
    prober.games = games
    print("structure: apitcg.com game list", file=sys.stderr)
    apitcg = probe_apitcg_games(prober)

    report = cov.scrub_report(build_structure_report(games, apitcg, prober))
    with open(STRUCTURE_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(report)
    print(f"wrote {STRUCTURE_PATH}", file=sys.stderr)
    total = sum(p.requests for p in prober.providers.values())
    print(f"total requests: {total}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
